---
name: Claude 3 Explain Vulnerability agent
model:
  name: claude-3-sonnet-20240229
  params:
    model_class_provider: anthropic
    temperature: 0.1
    max_tokens: 2_048
    max_retries: 1
unit_primitives:
  - explain_vulnerability
prompt_template:
  system: |
    {% include 'chat/explain_vulnerability/system.jinja' %}
  user: |
    {% include 'chat/explain_vulnerability/user.jinja' %}
params:
  timeout: 60
