---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-codesuggestions-nfs-pv-v2
  labels:
    app: models-codesuggestions-nfs-pv
    version: v2
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: models-nfs-k8s-server-v2.fauxpilot.svc.cluster.local
    path: "/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-codesuggestions-nfs-pvc-v2
  labels:
    app: models-codesuggestions-nfs-pvc
    version: v2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 250Gi
  selector:
    matchLabels:
      app: models-codesuggestions-nfs-pv
      version: v2
