---
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
    - if: $CI_API_V4_URL == "https://ops.gitlab.net/api/v4"

include:
  - local: /ci/gitlab-com.yml
    rules:
      - if: $CI_API_V4_URL == "https://gitlab.com/api/v4"
  - local: /ci/ops-gitlab-net.yml
    rules:
      - if: $CI_API_V4_URL == "https://ops.gitlab.net/api/v4"
  - project: 'gitlab-com/gl-infra/common-ci-tasks'
    ref: v1.72.1  # renovate:managed
    file: 'mirroring.yml'
