---
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

include:
  - local: /ci/gitlab-com.yml
    rules:
      - if: $CI_API_V4_URL == "https://gitlab.com/api/v4"
