version: "3"
services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-mage
    ports:
      - "7687:7687"
      - "7444:7444"
    command: ["--log-level=TRACE", "--query-execution-timeout-sec=6000"]
    volumes:
      - ./.tmp:/import
  lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "8000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687