version: '3.3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      # Can be created via ./setup.sh
      - .env
    ports:
      - "${API_EXTERNAL_PORT:-5000}:5000"
      - "${METRICS_EXTERNAL_PORT:-8082}:8082"
    hostname: ai-gateway
  redis:
    image: redis:7
    ports:
      - '6379:6379'
    command: redis-server --bind redis --loglevel warning --requirepass "$REDIS_PASS"
    env_file:
      - .env
