version: '3.3'
services:
#  triton:
#    image: moyix/triton_with_ft:22.09
#    command: bash -c "CUDA_VISIBLE_DEVICES=${GPUS} mpirun -n 1 --allow-run-as-root /opt/tritonserver/bin/tritonserver --model-repository=/model"
#    shm_size: '2gb'
#    volumes:
#      - ${MODEL_DIR}:/model
#    ports:
#      - "8000:8000"
#      - "8001:8001"
#      - "8002:8002"
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [gpu]
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      # Can be created via ./setup.sh
      - .env
    ports:
      - "${API_EXTERNAL_PORT:-5000}:5000"
  redis:
    image: redis:7
    ports:
      - '6379:6379'
    command: redis-server --bind redis --loglevel warning --requirepass "$REDIS_PASS"
    env_file:
      - .env

