version: '3.3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      # Can be created via ./setup.sh
      - .env
    ports:
      - "${API_EXTERNAL_PORT:-5000}:5000"
      - "${METRICS_EXTERNAL_PORT:-8082}:8082"
    hostname: ai-gateway
