# Source: ai-assist/templates/model-persistense-volumes.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-fauxpilot-nfs-pv
  labels:
    app: models-fauxpilot-nfs-pv
    helm.sh/chart: ai-assist-0.1.0
    app.kubernetes.io/name: ai-assist
    app.kubernetes.io/instance: ai-assist
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
    shard: "default"
    stage: "main"
    tier: "sv"
    type: "ai-assist"
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: model-nfs-k8s-server.fauxpilot.svc.cluster.local
    path: /
---
# Source: ai-assist/templates/model-persistense-volumes.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-fauxpilot-nfs-pvc
  labels:
    app: models-fauxpilot-nfs-pvc
    helm.sh/chart: ai-assist-0.1.0
    app.kubernetes.io/name: ai-assist
    app.kubernetes.io/instance: ai-assist
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
    shard: "default"
    stage: "main"
    tier: "sv"
    type: "ai-assist"
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: "500Gi"
  selector:
    matchLabels:
      app: models-fauxpilot-nfs-pv
---
