---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-fauxpilot-nfs-pv
  labels:
    app: models-fauxpilot-nfs-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: model-nfs-k8s-server.fauxpilot.svc.cluster.local
    path: "/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-fauxpilot-nfs-pvc
  labels:
    app: models-fauxpilot-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      app: models-fauxpilot-nfs-pv
