apiVersion: runway/v1.0.0-beta
kind: RunwayService
metadata:
  name: ai_gateway
  owner: code_creation
spec:
  image: "$CI_REGISTRY_IMAGE/model-gateway:${CI_COMMIT_SHORT_SHA}"
  request_timeout: 60
  observability:
    scrape_targets:
      - "localhost:8082"
  startup_probe:
    path: "/monitoring/healthz"
  liveness_probe:
    path: "/monitoring/healthz"
  scalability:
    min_instances: 9
    max_instances: 200
    max_instance_request_concurrency: 40
  resources:
    startup_cpu_boost: true
    limits:
      cpu: 2
      memory: 8G
