# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from duo_workflow.contract import (
    contract_pb2 as duo__workflow_dot_contract_dot_contract__pb2,
)


class DuoWorkflowStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteWorkflow = channel.stream_stream(
            "/DuoWorkflow/ExecuteWorkflow",
            request_serializer=duo__workflow_dot_contract_dot_contract__pb2.ClientEvent.SerializeToString,
            response_deserializer=duo__workflow_dot_contract_dot_contract__pb2.Action.FromString,
        )


class DuoWorkflowServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteWorkflow(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DuoWorkflowServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ExecuteWorkflow": grpc.stream_stream_rpc_method_handler(
            servicer.ExecuteWorkflow,
            request_deserializer=duo__workflow_dot_contract_dot_contract__pb2.ClientEvent.FromString,
            response_serializer=duo__workflow_dot_contract_dot_contract__pb2.Action.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "DuoWorkflow", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class DuoWorkflow(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteWorkflow(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/DuoWorkflow/ExecuteWorkflow",
            duo__workflow_dot_contract_dot_contract__pb2.ClientEvent.SerializeToString,
            duo__workflow_dot_contract_dot_contract__pb2.Action.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
