# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: duo_workflow/contract/contract.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n$duo_workflow/contract/contract.proto"s\n\x0b\x43lientEvent\x12-\n\x0cstartRequest\x18\x01 \x01(\x0b\x32\x15.StartWorkflowRequestH\x00\x12)\n\x0e\x61\x63tionResponse\x18\x02 \x01(\x0b\x32\x0f.ActionResponseH\x00\x42\n\n\x08response"W\n\x14StartWorkflowRequest\x12\x15\n\rclientVersion\x18\x01 \x01(\t\x12\x1a\n\x12workflowDefinition\x18\x02 \x01(\t\x12\x0c\n\x04goal\x18\x03 \x01(\t"5\n\x0e\x41\x63tionResponse\x12\x11\n\trequestID\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t"\xbf\x01\n\x06\x41\x63tion\x12\x11\n\trequestID\x18\x01 \x01(\t\x12\'\n\nrunCommand\x18\x02 \x01(\x0b\x32\x11.RunCommandActionH\x00\x12)\n\x0erunHTTPRequest\x18\x03 \x01(\x0b\x32\x0f.RunHTTPRequestH\x00\x12 \n\x0brunReadFile\x18\x04 \x01(\x0b\x32\t.ReadFileH\x00\x12"\n\x0crunWriteFile\x18\x05 \x01(\x0b\x32\n.WriteFileH\x00\x42\x08\n\x06\x61\x63tion"#\n\x10RunCommandAction\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t"\x1c\n\x08ReadFile\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t"/\n\tWriteFile\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\x12\x10\n\x08\x63ontents\x18\x02 \x01(\t"J\n\x0eRunHTTPRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x11\n\x04\x62ody\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_body2;\n\x0b\x44uoWorkflow\x12,\n\x0f\x45xecuteWorkflow\x12\x0c.ClientEvent\x1a\x07.Action(\x01\x30\x01\x42QZOgitlab.com/gitlab-org/ai-powered/ai-framework/duo_workflow_executor/pkg/serviceb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "duo_workflow.contract.contract_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals["DESCRIPTOR"]._options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"ZOgitlab.com/gitlab-org/ai-powered/ai-framework/duo_workflow_executor/pkg/service"
    )
    _globals["_CLIENTEVENT"]._serialized_start = 40
    _globals["_CLIENTEVENT"]._serialized_end = 155
    _globals["_STARTWORKFLOWREQUEST"]._serialized_start = 157
    _globals["_STARTWORKFLOWREQUEST"]._serialized_end = 244
    _globals["_ACTIONRESPONSE"]._serialized_start = 246
    _globals["_ACTIONRESPONSE"]._serialized_end = 299
    _globals["_ACTION"]._serialized_start = 302
    _globals["_ACTION"]._serialized_end = 493
    _globals["_RUNCOMMANDACTION"]._serialized_start = 495
    _globals["_RUNCOMMANDACTION"]._serialized_end = 530
    _globals["_READFILE"]._serialized_start = 532
    _globals["_READFILE"]._serialized_end = 560
    _globals["_WRITEFILE"]._serialized_start = 562
    _globals["_WRITEFILE"]._serialized_end = 609
    _globals["_RUNHTTPREQUEST"]._serialized_start = 611
    _globals["_RUNHTTPREQUEST"]._serialized_end = 685
    _globals["_DUOWORKFLOW"]._serialized_start = 687
    _globals["_DUOWORKFLOW"]._serialized_end = 746
# @@protoc_insertion_point(module_scope)
