---
name: Claude 3 Refactor Code agent
model:
  name: claude-3-5-sonnet-20241022
  params:
    model_class_provider: anthropic
    temperature: 0.1
    max_tokens: 2_048
    max_retries: 1
unit_primitives:
  - refactor_code
prompt_template:
  system: |
    {% include 'chat/refactor_code/system.jinja' %}
  user: |
    {% include 'chat/refactor_code/user.jinja' %}
params:
  timeout: 60
