---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-nfs-pvc
  labels:
    app: model-nfc-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      app: model-nfs-pv
---
apiVersion: batch/v1
kind: Job
metadata:
  name: model-loader-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: model-loader
          image: registry.gitlab.com/gitlab-org/modelops/applied-ml/ai-assist/ai-assist-api/model-loader:84188b5a58df11dbdb5ae500d018cd95c37e4da6
          env:
            - name: MODEL
              value: "codegen-16B-multi"
            - name: NUM_GPUS
              value: "1"
            - name: MODELS_DIR
              value: "/data/models"
          volumeMounts:
            - name: model-nfc-pvc-volume
              mountPath: /data/models
      volumes:
        - name: model-nfc-pvc-volume
          persistentVolumeClaim:
            claimName: model-nfs-pvc
      restartPolicy: Never