---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-serving
  labels:
    app: model-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-serving
  template:
    metadata:
      labels:
        app: model-serving
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: api
          image: registry.gitlab.com/gitlab-org/modelops/applied-ml/ai-assist/ai-assist-api/api:33b50f1472376768a54b11cebadf9d8530fa635d
          ports:
            - containerPort: 5000
          env:
            - name: TRITON_HOST
              value: "localhost"
            - name: TRITON_PORT
              value: "8001"
            - name: BYPASS_EXTERNAL_AUTH
              value: "true"

        - name: triton
          image: moyix/triton_with_ft:22.09
          ports:
            - containerPort: 8000
            - containerPort: 8001
            - containerPort: 8002
          env:
            - name: MODEL
              value: "fastertransformer"
            - name: MODEL_DIR
              value: "/model" # Use this path as it's hardcoded in Triton configs
            - name: TRITON_BIN
              value: "/opt/tritonserver/bin/tritonserver"
          command: ["/bin/bash", "-c", "--"]
          args:
            - "CUDA_VISIBLE_DEVICES=0 $(TRITON_BIN) --model-repository=$(MODEL_DIR) --model-control-mode=explicit --load-model=$(MODEL)"
          volumeMounts:
            - name: model-nfc-pvc-volume
              mountPath: /model
              readOnly: true
          resources:
            limits:
              nvidia.com/gpu: "1"
      volumes:
        - name: model-nfc-pvc-volume
          persistentVolumeClaim:
            claimName: model-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: model-k8s-serving
  labels:
    app: model-serving
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 5000
    - name: metrics
      port: 8082
      targetPort: 8002
  selector:
    app: model-serving