---
name: Claude 3 Epic reader agent
model:
  name: claude-3-sonnet-20240229
  params:
    model_class_provider: anthropic
    temperature: 0.1
    max_tokens: 2_048
    max_retries: 1
unit_primitives:
  - ask_epic
prompt_template:
  system: |
    {% include 'chat/epic_reader/system.jinja' %}
  user: |
    {% include 'chat/epic_reader/user.jinja' %}
  assistant: |
    {% include 'chat/epic_reader/assistant.jinja' %}
params:
  timeout: 60
