---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-nfs-server
  labels:
    app: model-nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-nfs-server
  template:
    metadata:
      labels:
        app: model-nfs-server
    spec:
      containers:
        - name: model-nfs-server
          image: gcr.io/google_containers/volume-nfs:0.8
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /exports
              name: nfs-models-volume
      volumes:
        - name: nfs-models-volume
          gcePersistentDisk:
            pdName: nfs-codesuggestions-models-disk
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: model-nfs-k8s-server
  labels:
    app: model-nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: model-nfs-server