---
# Create a StorageClass for a Google FileStore Volume
# https://cloud.google.com/filestore/docs/csi-driver
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: model-storageclass
  labels:
    {{- include "ai-assist.labels" . | nindent 4 }}
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: Immediate # Filestore is cross-AZ, no need to wait for binding
allowVolumeExpansion: true
parameters:
  tier: standard
  network: gitlab-ai-assist-network # This is the VPC the FileStore NFS server should be hosted on
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: model-storage-pvc
  labels:
    {{- include "ai-assist.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: model-storageclass
  resources:
    requests:
      storage: 1Ti
