apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-triton
  labels:
    app: model-triton
    {{- include "ai-assist.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.modelTriton.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: model-triton
    {{- include "ai-assist.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: model-triton
      {{- include "ai-assist.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: triton
          image: {{ .Values.modelTriton.triton.image.repository }}:{{ .Values.modelTriton.triton.image.tag | default .Chart.AppVersion }}
          ports:
            - containerPort: 8000
            - containerPort: 8001
            - containerPort: 8002
          env:
            - name: MODEL_REPOSITORY
              value: {{ quote .Values.modelTriton.triton.env.modelRepository }}
            - name: TRITON_BIN
              value: {{ quote .Values.modelTriton.triton.env.tritonBin }}
          command: ["/bin/bash", "-c", "--"]
          args:
            - "$(TRITON_BIN) --model-repository=$(MODEL_REPOSITORY)"
          volumeMounts:
            - name: models-fauxpilot-nfc-pvc-volume
              mountPath: /data
              readOnly: true
            - name: dshm
              mountPath: /dev/shm
          resources:
            limits:
              nvidia.com/gpu: "1"
          readinessProbe:
            httpGet: 
              path: /v2/health/ready
              port: 8000
            periodSeconds: 10
            initialDelaySeconds: 900
            timeoutSeconds: 1
            failureThreshold: 3
      volumes:
        - name: models-codesuggestions-nfc-pvc-volume
          persistentVolumeClaim:
            claimName: models-codesuggestions-nfs-pvc-v2
        - name: dshm
          emptyDir:
            sizeLimit: "2Gi"
            medium: "Memory"
---
apiVersion: v1
kind: Service
metadata:
  name: model-k8s-triton
  labels:
    app: model-triton
    {{- include "ai-assist.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: model-triton
    {{- include "ai-assist.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: 8080
      targetPort: 8001
    - name: metrics
      port: 8082
      targetPort: 8002
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-triton
  labels:
    release: prometheus
    {{- include "ai-assist.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: 30s
      port: metrics
  selector:
    matchLabels:
      app: model-triton
