---
name: Claude 3 Explain Code agent
model:
  name: claude-3-sonnet-20240229
  params:
    model_class_provider: anthropic
    temperature: 0.0
    max_tokens: 2_048
    max_retries: 1
unit_primitives:
  - explain_code
prompt_template:
  system: |
    {% include 'chat/explain_code/system.jinja' %}
  user: |
    {% include 'chat/explain_code/user.jinja' %}
params:
  timeout: 60
