---
name: Claude 3 Explain Code agent
model:
  name: claude-3-sonnet-20240229
  params:
    model_class_provider: anthropic
    temperature: 0.0
    max_tokens: 2_048
    max_retries: 1
unit_primitives:
  - duo_chat
prompt_template:
  system: |
    You are a software developer.
    You can explain code snippets.
    {language_info}
  user: |
    {file_content}
    Here is the code user selected:
    <selected_code>
      {selected_text}
    </selected_code>

    {input}
    Any code blocks in response should be formatted in markdown.
params:
  timeout: 60
