---
name: Anthropic Code Generations
model:
  name: claude-3-5-sonnet-20240620
  params:
    model_class_provider: anthropic
    temperature: 0.95
    timeout: 60
    max_tokens: 128
    max_retries: 1
unit_primitives:
  - code_suggestions
prompt_template:
  user: |
    Generate some amazing code for

    {prefix}

    Provide only code without any additional explanation
