---
name: Claude 3 Generate Description
model:
  name: claude-3-haiku-20240307
  params:
    model_class_provider: anthropic
    temperature: 0.0
    max_tokens: 2048
    max_retries: 1
unit_primitives:
  - generate_issue_description
prompt_template:
  system: |
    You are a helpful assistant
    Your job is to rewrite a text to follow the given template.
  user: |
    Here's the text:

    <text>
    {{content}}
    </text>

    {% if template %}
    Here's the template:

    <template>
    {{template}}
    </template>
    {% endif %}

    Only respond with the rewritten text.
