commonLabels:
  tier: "sv"
  stage: "main"
  shard: "default"

fauxPilot:
  labels:
    type: "code_suggestions"

modelGateway:
  labels:
    type: "code_suggestions"
  modelGateway:
    env:
      fastapiApiPort: "5052"
      tritonHost: model-k8s-triton-headless
      tritonPort: "8001"
      googleCloudProfiler: true

    flags:
      # See https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/issues/146#note_1424962628
      # for details of the chosen projects
      third_party_limited_ai_access: "46709700"

    image:
      repository: registry.gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/model-gateway
      tag: "" # this is set via helm command line arguments
  replicas: 12

modelK8SGateway:
  labels:
    type: "code_suggestions"

modelK8STriton:
  labels:
    type: "code_suggestions"

modelTriton:
  labels:
    type: "code_suggestions"
  replicas: 6
  triton:
    env:
      modelRepository: /data/models
      tritonBin: /opt/tritonserver/bin/tritonserver
    image:
      repository: registry.gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/tmp/triton-server
      tag: "" # this is set via helm command line arguments
    resources:
      limits:
        gpu: 2

modelStorage:
  labels:
    type: "code_suggestions"

prometheus-stackdriver-exporter:
  stackdriver:
    projectId: unreview-poc-390200e5
    metrics:
      typePrefixes: 'file.googleapis.com'
  serviceMonitor:
    enabled: true
    namespace: fauxpilot
    additionalLabels:
      release: prometheus
  serviceAccount:
    name: model-gateway-serviceaccount

serviceAccount:
  labels:
    type: "code_suggestions"
  # The service account email to use with this account
  iamServiceAccountEmail:
