---
name: Claude 3 ReAct Chat agent
model:
  name: claude-3-5-sonnet-20240620
  params:
    model_class_provider: anthropic
    temperature: 0.1
    max_tokens: 4_096
#    TODO: thoroughly proofread all tools
    tools:
      - name: issue_reader
        description: |
          This tool retrieves the content of a specific issue ONLY if strict usage conditions are met:
          1. A valid issue ID must be provided
          2. User must be actively viewing a specific issue URL or provide a specific URL
          
          Do NOT attempt to search for issues based on descriptions, keywords, or user questions.
          Will reject any input without a valid identifier.
          
          Example usage:
          Thought: You have access to the same resources as user who asks a question. Question is about the content of an issue so you need to use issue_reader tool to retrieve and read issue. Based on this information you can present final answer about issue.
          Action: issue_reader
          Action Input: Please identify the author of /#123 issue
        input_schema:
          type: object
          properties:
            thought:
              type: string
              description: The reasoning process for using this tool
            action:
              type: string
              description: Should always be "issue_reader"
            action_input:
              type: string
              description: The original question/request about a specific issue. Format should be like 'Please identify the author of /#123 issue'

      - name: merge_request_reader
        description: |
          This tool retrieves the content of a specific merge request ONLY if strict usage conditions are met:
          1. A valid merge request ID must be provided
          2. User must be actively viewing a specific merge request URL or provide a specific URL
          
          Do NOT attempt to search for or identify merge requests based on descriptions, keywords, or user questions.
          Will reject any input without a valid identifier.
          
          Example usage:
          Thought: You have access to the same resources as user who asks a question. Question is about the content of a merge request, so you need to use merge_request_reader tool to retrieve and read merge request. Based on this information you can present final answer about merge request.
          Action: merge_request_reader
          Action Input: Please identify the author of /#123 merge request
        input_schema:
          type: object
          properties:
            thought:
              type: string
              description: The reasoning process for using this tool
            action:
              type: string
              description: Should always be "merge_request_reader"
            action_input:
              type: string
              description: The original question/request about a specific merge request. Format should be like 'Please identify the author of /#123 merge request'

      - name: commit_reader
        description: |
          This tool retrieves the content of a specific commit ONLY if strict usage conditions are met:
          1. A valid commit ID must be provided
          2. User must be actively viewing a specific commit URL or provide a specific URL
          
          Do NOT attempt to search for or identify commits based on descriptions, keywords, or user questions.
          Will reject any input without a valid identifier.
          
          Example usage:
          Thought: You have access to the same resources as user who asks a question. Question is about the content of a commit, so you need to use commit_reader tool to retrieve and read commit. Based on this information you can present final answer about commit.
          Action: commit_reader
          Action Input: Please identify the author of /#123 commit
        input_schema:
          type: object
          properties:
            thought:
              type: string
              description: The reasoning process for using this tool
            action:
              type: string
              description: Should always be "commit_reader"
            action_input:
              type: string
              description: The original question/request about a specific commit. Format should be like 'Please identify the author of /#123 commit'

      - name: build_reader
        description: |
          This tool retrieves the content of a specific build ONLY if strict usage conditions are met:
          1. A valid build ID must be provided
          2. User must be actively viewing a specific build URL or provide a specific URL
          
          Do NOT attempt to search for or identify builds based on descriptions, keywords, or user questions.
          Will reject any input without a valid identifier.
          
          Example usage:
          Thought: You have access to the same resources as user who asks a question. The question is about a build, so you need to use build_reader tool. Based on this information you can present final answer.
          Action: build_reader
          Action Input: Please identify the author of &123 build
        input_schema:
          type: object
          properties:
            thought:
              type: string
              description: The reasoning process for using this tool
            action:
              type: string
              description: Should always be "build_reader"
            action_input:
              type: string
              description: The original question/request about a specific build. Format should be like 'Please identify the author of &123 build'

      - name: gitlab_documentation
        description: |
          This tool is beneficial when you need to answer questions concerning GitLab and its features.
          Questions can be about GitLab's projects, groups, issues, merge requests, epics, work items, 
          milestones, labels, CI/CD pipelines, git repositories, and more.
          
          Example usage:
          Thought: Question is about inner working of GitLab. gitlab_documentation tool is the right one for the job.
          Action: gitlab_documentation
          Action Input: set up project
        input_schema:
          type: object
          properties:
            thought:
              type: string
              description: The reasoning process for using this tool
            action:
              type: string
              description: Should always be "gitlab_documentation"
            action_input:
              type: string
              description: The original question about GitLab functionality, kept concise without punctuation

    max_retries: 1
unit_primitives:
  - duo_chat
prompt_template:
  system: |
    {% include 'chat/react/system_tools.jinja' %}
  user: |
    {% include 'chat/react/user.jinja' %}
  assistant: |
    {% include 'chat/react/assistant.jinja' %}
params:
  timeout: 30
  stop:
    - "Observation:"