---
name: Claude 3 ReAct Chat agent
model:
  name: claude-3-5-sonnet-20240620
  params:
    model_class_provider: anthropic
    temperature: 0.0
    max_tokens: 2_048
    max_retries: 1
unit_primitives:
  - duo_chat
params:
  timeout: 60
  stop:
    - "Observation:"
