---
environments:
  gstg:
    kubeContext: gke_unreview-poc-390200e5_us-central1-c_ai-assist-test
    values:
      - environment/gstg/values.yaml

  gprd:
    kubeContext: gke_unreview-poc-390200e5_us-central1-c_ai-assist
    values:
      - environment/gprd/values.yaml

  runner:
    kubeContext: gke_unreview-poc-390200e5_us-central1-c_ai-assist-test
    values:
      - environment/runner/values.yaml

---

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 600

repositories:
  - name: gitlab
    url: https://charts.gitlab.io
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: ai-assist
    namespace: fauxpilot
    chart: ./ai-assist
    values:
      - {{ .Values.aiassist | toYaml | indent 8 | trim}}

  - name: gitlab-runner
    installed: {{ eq .Environment.Name "runner" | toYaml }}
    namespace: gitlab-runner
    createNamespace: true
    chart: gitlab/gitlab-runner
    version: 0.52.0
    values:
      - {{ .Values.runner | toYaml | indent 8 | trim}}
