---
environments:
  gstg:
    kubeContext: gke_unreview-poc-390200e5_us-central1-c_ai-assist-test
    values:
      - environment/gstg/values.yaml

  gprd:
    kubeContext: gke_unreview-poc-390200e5_us-central1-c_ai-assist
    values:
      - environment/gprd/values.yaml
---

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 600

repositories:
  - name: gitlab
    url: https://charts.gitlab.io
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: ai-assist
    namespace: fauxpilot
    chart: ./ai-assist
    values:
      - {{ .Values.aiassist | toYaml | indent 8 | trim}}

  - name: gitlab-runner
    installed: {{ eq .Environment.Name "gstg" | toYaml }}
    namespace: gitlab-runner
    createNamespace: true
    chart: gitlab/gitlab-runner
    version: 0.52.0
    values:
      - runnerRegistrationToken: {{ requiredEnv "RUNNER_REGISTRATION_TOKEN" }}
        gitlabUrl: https://gitlab.com
        rbac:
          create: true
        runners:
          config: |
            [[runners]]
              [runners.kubernetes]
                namespace = "gitlab-runner"
                image = "ubuntu:22.04"
                allowed_pull_policies = ["always", "if-not-present", "never"]
                pull_policy = ["if-not-present"]

                # Very high resource usage to allow these jobs to 
                # handle resource intensive builds
                memory_request = "1Gi"
                memory_limit = "30Gi"

                cpu_limit = "4"
                cpu_request = "2"

                ephemeral_storage_request = "40Gi"
                ephemeral_storage_limit = "100Gi"

                [runners.kubernetes.node_tolerations]
                  "type=ci-runners" = "NoSchedule"

