---
environments:
  runner:
    kubeContext: gke_unreview-poc-390200e5_us-central1-c_ai-assist-test
    values:
      - environment/runner/values.yaml

---

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 600

repositories:
  - name: gitlab
    url: https://charts.gitlab.io
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: gitlab-runner
    namespace: gitlab-runner
    createNamespace: true
    chart: gitlab/gitlab-runner
    version: 0.52.0
    values:
      - {{ .Values.runner | toYaml | indent 8 | trim}}
      - runnerRegistrationToken: '{{ requiredEnv "RUNNER_REGISTRATION_TOKEN" }}'
